### ISSUE TITLE
Unable to build for bare metal AVR32

### ISSUE THREAD

**Issue by denravonska** [wolfSSL/wolfssl#1518]
I'm trying to use TLS with wolfMQTT and wolfSSL for my bare metal AVR32 device. I can configure the build system but it fails when compiling:

```
wolfSSL/configure
   --enable-leanpsk
   --enable-smallstack
   --enable-ecc
   --enable-des3
   --disable-shared
   --disable-examples
   --disable-fips
   --disable-selftest
   --disable-dh
   --disable-harden
   --enable-tlsv10
   --host=avr32
   --target=avr32
   CFLAGS="-Wpointer-arith -mrelax -mno-cond-exec-before-reload -Wstrict-prototypes -Werror-implicit-function-declaration -march=ucr3fp -mpart=uc3c2512c -mhard-float -std=gnu99 -ffunction-sections -fdata-sections"
...

  CC       src/src_libwolfssl_la-internal.lo
  CC       src/src_libwolfssl_la-wolfio.lo
In file included from wolfSSL/src/internal.c:32:
wolfSSL/wolfssl/internal.h:1163: error: 'DES3_KEY_SIZE' undeclared here (not in a function)
```
Any idea what this could be?

**Comment by dgarske** [comment]
Hi denravonska,

Thanks for this report. There was a typo in `wc_encrypt.h` with the `NO_DES3` define. I've pushed a fix for it to PR #1519. You can find the single line change in this commit: https://github.com/wolfSSL/wolfssl/pull/1519/commits/04626c6a1f1bed7f61bef72d37eb5ce69555b39e

Thanks,
David Garske, wolfSSL

**Comment by denravonska** [comment]
@dgarske Thanks, that got me past the configure stage. I'm getting stuck at there being no target for `cyassl/options.h` but I remember seeing a fix for that before.

**Comment by dgarske** [comment]
Hi denravonska,

My guess is since you are cross-compiling that file isn't getting generated correctly. You can just create it based on the template and leave blank like `cp ./cyassl/options.h.in ./cyassl/options.h`. That file only applies if you are using the older cyassl style API's.

If you do need it then you can populate it with the defines from `./wolfssl/options.h`.

Thanks,
David Garske, wolfSSL
