### ISSUE TITLE
Lock full after receiving connection from few clients

### ISSUE THREAD

**Issue by mdczaplicki** [wolfSSL/wolfssl#1862]
Any thoughts on this one?
https://github.com/wolfSSL/wolfssl-py/issues/5#issue-360289777
I think it is mainly related to python's threading and your's library.  
There is a similar problem already on stackoverflow.
https://stackoverflow.com/questions/21825291/threading-issues

**Comment by kaleb-himes** [comment]
In brief, the problem is caused by repeated locking of a fast mutex, and solved by using a recursive mutex. The default pthread_mutex_t is not recursive. Were you able to resolve this locally? If so, we would welcome a patch via a pull request on the wolfSSL Python solution. If you do decide to open a PR just shoot us an email at support@wolfssl.com and we will send over a contributor agreement for review and signing.

Warm Regards,

- K
