### ISSUE TITLE
9 Lives of Bleichenbacher's CAT - vulnerability

### ISSUE THREAD

**Issue by attritionorg** [wolfSSL/wolfssl#1949]
Regarding this recent disclosure: http://cat.eyalro.net/

They say they contacted the affected vendors, which include WolfSSL. Do you have a fixing commit or any references for this attack?

Thank you!

**Comment by kaleb-himes** [comment]
Hi @attritionorg,

Thank you for reaching out to wolfSSL about the recent disclosure! The commit that addresses the issue is undergoing our review process and can be found here: https://github.com/wolfSSL/wolfssl/pull/1950

If you have any other questions/concerns/comments please do not hesitate to contact us at support@wolfssl.com for best response times!

**Comment by attritionorg** [comment]
Excellent, will follow that PR. Thanks for the quick response!

**Comment by pedrohc** [comment]
FYI, CVE-2018-16870 was assigned this issue.
