### ISSUE TITLE
-m32 flag added to AM_CFLAGS

### ISSUE THREAD

**Issue by thorsten-klein** [wolfSSL/wolfssl#1985]
Hello,
unfortunately not all compilers are supporting the `-m32` flag. Especially the arm compilers do not support. 
The following code from configure.ac leads to compilation error `unrecognized command line option '-m32'`
```
AM_CFLAGS="$AM_CFLAGS -DNO_64BIT -DNO_CURVED25519_128BIT -m32"
AM_LDFLAGS="$AM_LDFLAGS -m32"
```

can you please remove the `-m32` flag. If required by compilers it should be added via `CFLAGS` / `CXXFLAGS` / `LDFLAGS`

```
AM_CFLAGS="$AM_CFLAGS -DNO_64BIT -DNO_CURVED25519_128BIT"
AM_LDFLAGS="$AM_LDFLAGS"
```

**Comment by dgarske** [comment]
@thorsten-klein : We have removed the `--enable-32bit` option. It was added to help with internal testing, however even then it wasn't working correctly due to sizeof long and long/long tests. If `-m32`  is designed (to force 32-bit instructions) it must be used with `./configure CFLAGS="-m32" LDFLAGS="-m32"`
