### ISSUE TITLE
Clarification on usage with atecc608a module and wolfMQTT

### ISSUE THREAD

**Issue by Aareksio** [wolfSSL/wolfssl#2250]
Hi,

I'm trying to setup raspberry pi with the most simple application that connects to AWS IoT using encryption provided by atecc608a.

Could you please provide updated example of usage with atecc608a module (and ideally further, with wolfMQTT)? 

Reading through code, documentation and issues, I found myself lost, a few examples:

- not so long ago in an issue, it was revealed you use a [fork of cryptoauth lib, branch named actatls](https://github.com/dgarske/cryptoauthlib/tree/atcatls), while in the changelog of source repository you may find a line: [Removed atcatls related files as they were of limited value.](https://github.com/MicrochipTech/cryptoauthlib/blob/f4306def06a54be1a49969523d6561be366c7372/docs/html/index.html#L167)

- it is unclear whether one should use `pk_callbacks` or `ws_ecc_*` API

- compiling with `#include "wolfssl/wolfcrypt/port/atmel/atmel.h"` as per [example](https://github.com/wolfSSL/wolfssl/blob/master/IDE/Espressif/ESP-IDF/examples/wolfssl_client/main/client-tls.c#L62) leads to undefined references

As my understanding of C code, not to mention wolfSSL, is fairly limited, I'd appreciate a working example or up-to-date clarification on how to use the library with the module.

**Comment by dgarske** [comment]
Hi Aareksio,

The CryptoAuthLib support for the atcatls API's were removed by Atmel, so we pulled them into a branch we have here:
https://github.com/dgarske/cryptoauthlib/tree/atcatls

The wolfSSL TLS use of the ATECC chip is currently supported via the PK callbacks (HAVE_PK_CALLBACKS). The best information can be found here:
https://github.com/wolfSSL/wolfssl/tree/master/wolfcrypt/src/port/atmel

You'll need to build with `WOLFSSL_ATECC508A` and `HAVE_PK_CALLBACKS` and call `atcatls_set_callbacks(ctx)` to setup the PK callbacks. To debug add `WOLFSSL_ATECC508A_DEBUG`.

The `wolfCrypt_Init()` function will call `atmel_init()` in atmel.c to setup the hardware. You can customize the ATECC slots using macros here: https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/wolfcrypt/port/atmel/atmel.h#L47

Make sure and use the latest GitHub master as there were some recent ATECC fixes merged:
The following fixes have been made since release:
https://github.com/wolfSSL/wolfssl/pull/2199
https://github.com/wolfSSL/wolfssl/pull/2172
https://github.com/wolfSSL/wolfssl/pull/2086
https://github.com/wolfSSL/wolfssl/pull/2052
https://github.com/wolfSSL/wolfssl/pull/2034

Thanks,
David Garske, wolfSSL
