### ISSUE TITLE
"wolfSSL_CTX_set_verify" can't work in enclave

### ISSUE THREAD

**Issue by RyukerLiu** [wolfSSL/wolfssl#2405]
I'm trying to use mutual authentication with wolfssl in SGX.

I have try on [normal example](https://github.com/wolfSSL/wolfssl-examples/tree/master/tls) with mutual authentication. Seem it works with below api to enable mutual authentication.
` wolfSSL_CTX_set_verify(ctx, SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT, 0);`

But when I try to enable mutual authentication with [Linux_SGX exmaple](https://github.com/wolfSSL/wolfssl-examples/tree/master/SGX_Linux), the api can't work.

I've also add wolfSSL_accpet() as normal example to check is the connect successful.
and add wolfSSL_set_verify api in enclave. But the tls_client without cert can still connect to tls server successfully. Seems mode "SSL_VERIFY_FAIL_IF_NO_PEER_CERT" have no function.

app code:
```
    sgxStatus = enc_wolfSSL_CTX_set_verify(id,
            ctx, SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT, 0); 
    if (sgxStatus != SGX_SUCCESS)
    {   
        printf("Error set verify\n");
        return EXIT_FAILURE;
    }   
```

enclave code:
```
void enc_wolfSSL_CTX_set_verify(WOLFSSL_CTX* ctx, int mode, VerifyCallback verify_callback)
{
    if(sgx_is_within_enclave(ctx, wolfSSL_CTX_GetObjectSize()) != 1)
        abort();

#if defined(WOLFSSL_STATIC_MEMORY)
    checkHeapHint(ctx, NULL);
#endif

    wolfSSL_CTX_set_verify(ctx, mode, verify_callback);
}
```

Any help would be appreciated.

**Comment by kaleb-himes** [comment]
@RyukerLiu,

To setup mutual auth within the enclave you will need to add:

A method to store a key and cert inside the enclave or pass them in. Then (depending on if you are running server or client in the enclave)

CLIENT:
wolfSSL_CTX_load_verify_locations // Load the SERVERS root ca (the root CA that signed the servers leaf-cert or chain of certs)
wolfSSL_CTX_use_PrivateKey_file // Load the private key for the CLIENTS leaf cert
wolfSSL_CTX_use_certificate_file // Load the CLIENTS leaf cert

SERVER:
wolfSSL_CTX_load_verify_locations // Load the CLIENTS root ca (the root CA that signed the clients leaf-cert or chain of certs)
wolfSSL_CTX_use_PrivateKey_file // Load the private key for the SERVERS leaf cert
wolfSSL_CTX_use_certificate_file // Load the SERVERS leaf cert

Now call ```wolfSSL_CTX_set_verify``` in both client and server apps. (assuming wolfSSL is being used in both otherwise make sure the non-SGX side is requesting a cert and does support mutual auth).

Cheers,

K
