### ISSUE TITLE
Correct possible memory leaks in wolfssl-3.8.0

### ISSUE THREAD

**Issue by dogbert2** [wolfSSL/wolfssl#308]
Hello All,

	In reviewing source code in directory 'src', file 'internal.c'
in function 'GetEntropy()', there appears to be a potential memory
leak if rngMutex returns NULL after it's call to XMALLOC.  The 
patch file below should address/correct this issue:

--- internal.c.orig     2016-02-11 09:17:05.406480769 -0800
+++ internal.c  2016-02-11 09:17:08.636891338 -0800
@@ -286,8 +286,10 @@
 
     if (rngMutex == NULL) {
         if ((rngMutex = (wolfSSL_Mutex*)XMALLOC(sizeof(wolfSSL_Mutex), 0,
-                        DYNAMIC_TYPE_TLSX)) == NULL)
+                        DYNAMIC_TYPE_TLSX)) == NULL) {
+            XFREE(rng, NULL, DYNAMIC_TYPE_TLSX);
             return DRBG_OUT_OF_MEMORY;
+       }
         InitMutex(rngMutex);
     }
 
=======================================================================

	In reviewing source code in directory 'src', file 'ssl.c'
in function 'PemToDer()', there appears to be a potential memory
leak if Base64_Decode() returns < 0.  The patch file below should
address/correct this issue:

--- ssl.c.orig  2016-02-11 09:36:22.350522408 -0800
+++ ssl.c       2016-02-11 09:40:11.091594222 -0800
@@ -2734,8 +2734,10 @@
     der->length = (word32)neededSz;
 
     if (Base64_Decode((byte*)headerEnd, (word32)neededSz,
-                      der->buffer, &der->length) < 0)
+                      der->buffer, &der->length) < 0) {
+        XFREE(der->buffer, heap, dynamicType); /* release memory prev allocated */
         return SSL_BAD_FILE;
+    }
 
     if (header == BEGIN_PRIV_KEY && !encrypted_key) {
         /* pkcs8 key, convert and adjust length */

=======================================================================

There may be other locations (below line 2734) in the function where it
returns and the memory assigned to variable 'der->buffer' is not released.		 

Bill Parker (wp02855 at gmail dot com)

**Comment by dgarske** [comment]
Hello Bill, 

I've carefully reviewed the two reports and no memory leak was found, based on your feedback we will do some cleanup in those areas so its better documented how those alloc's are handled.

The first report in GetEntropy is against buffers defined outside the function statically. The intention is to have those buffers allocated the first time and continue to be used for subsequent calls. We will cleanup so the naming of the static variables is better and also add a comment about the purpose of those allocs.

The second report for PemToDer is also misleading since it allocates the der.buffer inside, however all callers to PemToDer correctly handle freeing der.buffer afterwards (failure or not). I have started a refactor to add a FreeDer and re-organize the use of the der buffers for clarity.

Thanks for these reports and please let us know if you find anything else.

David Garske, wolfSSL
