### ISSUE TITLE
ER: Consider adding a "shouldFreeFPCache" option to ecc_sign and ecc_verify 

### ISSUE THREAD

**Issue by aburks** [wolfSSL/wolfssl#44]
Consider adding a "shouldFreeFPCache" option to the `ecc_sign` and `ecc_verify` functions that frees the fixed point cache after the operation completes if set to `true`. Additionally, this flag will more clearly communicate that there is a global cache that may be using heap space.

**Comment by toddouska** [comment]
The FP Cache is optional at build time.  If it's turned on at build time that typically means the user has traded more RAM for the cache for reduced computation times.  We also expose an API to free the cache wc_ecc_fp_free() if the user wishes to do so at any time.  I'm not sure adding an API parameter to an existing API is the right solution here.

The FP cache is only helpful if the RAM is held, that is, there's an upfront cost to building the cache points that isn't utilized if it's immediately free'd.  In that case, turning off the FP Cache at build time is probably a better solution overall because less memory is used/held and the performance will be better.
