### ISSUE TITLE
se050 and GCM

### ISSUE THREAD

**Issue by MalikAlmazrua** [wolfSSL/wolfssl#4528]
https://github.com/wolfSSL/wolfssl/blob/2745f394e5234fbf8d237b3796398029b16f15de/wolfssl/wolfcrypt/aes.h#L178

NXP se050 does not support GCM. why do I have to define HAVE_AESGCM in order to use AES CBC or CTR in the library?

**Comment by dgarske** [comment]
Hi @MalikAlmazrua,

You can build with AES CBC and CTR only (no GCM). All modes can be built and used independently. What build error are you seeing and what build options are you using? Perhaps the issue is with TLS v1.3 and it only supporting AEAD ciphers like AES-GCM and ChaCha20/Poly1305?

Thanks,
David Garske, wolfSSL
