### ISSUE TITLE
[Bug]: DTLS Invalid Version

### ISSUE THREAD

**Issue by bathooman** [wolfSSL/wolfssl#5226]
### Version

5.3.0

### Description

**Configure Options**

> ./configure --disable-asm --enable-singlethreaded --enable-dtls --enable-dtls-mtu --enable-psk --disable-extended-master --prefix=$(pwd)/build --enable-static --enable-opensslextra --enable-debug

**Expected behavior**

The DTLS 1.2 RFC states that:

> There is no DTLS 1.1.

> DTLS 1.2 and 1.0 clients MUST use the version to indicate packet formatting.

> Unlike TLS, DTLS is resilient in the face of invalid records (e.g., invalid formatting, **length**, MAC, etc.).  In general, invalid records SHOULD be silently discarded, thus preserving the association; however, an error MAY be logged for diagnostic purposes.

**Actual behavior**    

Since DTLS 1.1 does not exist, any record with that version is considered wrongly formatted and should be discarded. However, for the `CH0` and `CH2`, one can provide the value `fe fe` (1.1) as the version for both the `record version` and `handshake version` and still complete the handshake. Moreover, the record version for the `HVR` can be assigned `fe fe` without complaints from the client when the `HVR` is being processed.

In the following, you can find the Wireshark log.

[version-witness.zip](https://github.com/wolfSSL/wolfssl/files/8869503/version-witness.zip)

**Comment by rizlik** [comment]
Hi @bathooman,
Sorry, this took a while.
I think that considering a CH/SH or HVR record wrongly formatted based on the version isn't a good idea, as this field can be used for version negotiation and can lead to protocol ossification.
Moreover, if you look at the errata of 4103 [RFC 6347](https://www.rfc-editor.org/errata/eid4103), the (contradictory) constraints of the HVR protocol version were relaxed, so the client shouldn't do any assumptions based on the protocol version of the HVR.

Nevertheless, the handshake shown in the witness you provided was indeed wrong, because the server replied with a higher version of the protocol to the client. Also, as v1.1 can be considered a wrong version of the protocol, I think it's ok to refuse to accept that version.

#5276 should address both those problems and improve dtls downgrade support in wolfSSL.

Could you confirm that it fixes the issue?

**Comment by bathooman** [comment]
Hello,

In my recent tests, I re-discovered this issue again. It seems that it is not solved yet. So, I thought to reopen this issue.

### Version

v5.6.3-stable

**Actual behavior**    

You can still complete a handshake with bogus record versions (e.g. DTLS 1.1 or even 00 01). For the reference, OpenSSL at least checks the first byte of the version (Major version) for correctness.

In the following, you can find the Wireshark log.

[record-version-examples.zip](https://github.com/wolfSSL/wolfssl/files/13428376/record-version-examples.zip)
