### ISSUE TITLE
Doxygen documentation is for "My Project"?

### ISSUE THREAD

**Issue by rliebscher** [wolfSSL/wolfssl#5980]
I guess you probably want to have some other name there?
See for example https://www.wolfssl.com/doxygen/index.html

Just set an own name instead using the default.
https://github.com/wolfSSL/wolfssl/blob/08a988f55735e7d18f0eb01e84294089706016b6/doc/formats/html/Doxyfile#L33

**Comment by dgarske** [comment]
Hi @rliebscher ,

Thank you for the report. I don't think it gets used for our doxy generation, since I don't see it in the HTML or PDF.

The resulting HTML is posted daily here:
https://www.wolfssl.com/documentation/manuals/wolfssl/

The PDF daily here:
https://www.wolfssl.com/documentation/manuals/wolfssl/wolfSSL-Manual.pdf

Also we use the script / doxyfile from here to generate the manuals:
https://github.com/wolfSSL/documentation/tree/master/wolfSSL

Thanks,
David Garske, wolfSSL
