### ISSUE TITLE
Encrypted Client Hello

### ISSUE THREAD

**Issue by git001** [wolfSSL/wolfssl#6461]
### Version

Future version

### Description

Hi.
Is there any plan to add [TLS Encrypted Client Hello](https://datatracker.ietf.org/doc/draft-ietf-tls-esni/) into wolfssl.

This could be related to the haproxy Feature request [ECH (Encrypted client hello) support](https://github.com/haproxy/haproxy/issues/1924)

**Comment by dgarske** [comment]
Hi @git001 ,

We already support ECH (Encrypted Client Hello) since v5.6.0. It is also known as Encrypted SNI, which uses HPKE. See `--enable-hpke`.

Blog we did on it with details:

https://www.wolfssl.com/encrypted-client-hello-ech-now-supported-wolfssl/#:~:text=ECH%20(Encrypted%20Client%20Hello)%20is,during%20the%20normal%20TLS%20handshake.

Let us know if you have any issues or questions.

Thanks,
David Garske, wolfSSL

**Comment by git001** [comment]
Thank you for your answer
