### ISSUE TITLE
Password length limit for wc_PBKDF2 in FIPS mode

### ISSUE THREAD

**Issue by trampster** [wolfSSL/wolfssl#6570]
### Version

5.6.3 fips-ready

### Description

Calling wc_PBKDF2 in order to turn a password into a key in FIPS mode requires the password to be 112 bits (14 ascii characters).

This is because wc_PBKDF2 calls wc_HmacSetKey with the password as the key, and it requires the key length to be >= HMAC_FIPS_MIN_KEY

```
#ifdef HAVE_FIPS
    if (length < HMAC_FIPS_MIN_KEY) {
        WOLFSSL_ERROR_VERBOSE(HMAC_MIN_KEYLEN_E);
        return HMAC_MIN_KEYLEN_E;
    }
#endif
```

Was it intended that wc_PBKDF2 only be able to generate keys for passwords 14 characters or longer, is was this an unintended side effect of it calling wc_HmacSetKey?

Is this actually a FIPS restriction, (effectively forcing all passwords to be 14 characters or longer).

We are using this to import an encrypted file created by a tool owned by another organization. Our customers want to be able to open these existing files (the majority of which will have passwords shorter than 14 characters) but they also demand FIPS.

Do you have any recommendations for how to proceed?

**Comment by embhorn** [comment]
Hello @trampster 

Thanks for contacting wolfSSL Support. The minimum password length is indeed a FIPS requirement.

In some applications you can do some some kind of password stretching or padding to accommodate the rule, but this would break interoperability, i.e.  any other WPA or WPA2 (wireless network) implementation won’t know to stretch it the way we are so it still won’t work to interop between FIPS and non_FIPS libraries and WPA/WPA2 authentication which expects a non-stretched version to accept.

I'll check with the team about using padding to accomplish what you are describing.

Thanks,
Eric - wolfSSL Support

**Comment by kaleb-himes** [comment]
@trampster,

As my colleague suggested you can stretch a key/password prior to calling `wc_PBKDF2` using either padding or hashing it in advance of the PBKDF2 call to get it to the minimum length requirement for FIPS mode. The only problem with this approach is that the HMAC call will end up computing a hash over both the short key + padded data or the advanced hash of the short key and any third-party implementation of PBKDF2 without the same stretching mechanism will end up with a different hash value and think that the wrong password has been keyed in.

One example of this was a customer that had printers with a FIPS requirement running wolfCrypt in FIPS mode but the office router did not have a FIPS requirement and was using some other proprietary WPA2 enterprise implementation. They applied padding to their 5-byte Wifi password padding it out to 14-bytes for the FIPS requirement but the router wouldn't allow the printers to connect because the HMAC hash of the [5-byte+padding] did not match the routers HMAC hash of the raw 5-byte password.

The end solution was updating the Wifi password to be 14-bytes or greater so padding or stretching of the key was not necessary and the FIPS compliant printers could connect to the non-FIPS compliant router.

Please let us know if this is helpful and please let us know a little more about your use-case, we would love to understand how we can help.

- K

**Comment by trampster** [comment]
Thanks for your reply, as we have no control over the source of the data we have concluded we must communicate to our customers that we can no longer import files with passwords shorter than 14 bytes.
