### ISSUE TITLE
[Bug]: wolfSSL_connect returns bad error code

### ISSUE THREAD

**Issue by 4e4o** [wolfSSL/wolfssl#6678]
### Version

master

### Description

Maybe process goes faster if i open issue.
Exactly the same issue as https://github.com/wolfSSL/wolfssl/issues/5325 but with wolfSSL_connect_TLSv13.
Pull request: https://github.com/wolfSSL/wolfssl/pull/6677

### Reproduction steps

Reproduced with this https://github.com/wolfSSL/wolfssl-examples/blob/master/tls/client-tls-nonblocking.c example.

**Comment by kareem-wolfssl** [comment]
Hi @4e4o ,

Thanks for the report, and for your PR.  We do require a signed contributor agreement to accept third-party contributions, and we don't file agreements for minor changes.
Please let me know if you have any further contributions planned.  If you do, we can file a contributor agreement.  Otherwise, we will treat your PR as a bug report.

Thanks,
Kareem

**Comment by JacobBarthelmeh** [comment]
Closing in favor of PR6692
