### ISSUE TITLE
[Bug]: IoTSafe File ID, ID Size

### ISSUE THREAD

**Issue by jezzep** [wolfSSL/wolfssl#6912]
### Contact Details

jeremy.norris@zariot.com

### Version

latest

### Description

Hiya,

I note the following in the iotsafe.c:

          _int wolfIoTSafe_GetCert_ex(**uint8_t *id, uint16_t id_sz,** unsigned char *output,
                  unsigned long sz)
          {
              XMEMSET(output, 0, sz);
              return iotsafe_readfile(id, id_sz, output, (word32)sz);
          }
          
          int wolfIoTSafe_GetCert(uint8_t id, unsigned char *output, unsigned long sz)
          {
              return wolfIoTSafe_GetCert_ex(&id, **1,** output, sz);
          }_

If you see the WolfIoTSafe_GetCert() call you can see that it doesn't support ID sizes great than one byte. As a SIM designer, this isn't correct and against the IoTSafe specification, that allows variable sizes. The function should take a strig array for ID and the length should be used and not fixed as 1 byte.

I'm happy to help and can provide a test card with IoTSafe installed with the ID being a longer size, if that helps testing?

BR
Jerry

**Comment by anhu** [comment]
Hi @jezzep, 

I'd like to invite you to continue this conversation via our technical support ticketing system as this might involve disclosure of personal information about yourself in order to facilitate sending of the test card as you suggested.  To do so, please send an email to support@wolfssl.com with a link to this github issue as a reference.  In that message please also tell us a bit about yourself and your company Zariot.  We'd also love to hear about your project and what you are trying to achieve. 

I will now close this ticket and await your message at support@wolfssl.com.

Warm regards, Anthony
